name: "Push docs to gh-pages"

on:
  release:
    types: [published]

# Declare default permissions as read only.
permissions: read-all

jobs:
  push-gh-pages:
    env:
      ruby_version: "3.1"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Install Ruby ${{ env.ruby_version }}
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true
      - name: Install toys
        run: gem install --no-document toys
      - name: Publish docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          toys release publish-gh-pages --verbose < /dev/null
